import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Stack ,Text,HStack} from '@chakra-ui/react'
import { useAppSelector } from '@/hooks/dispatchSelectHook'
import { RootState } from '@/services/redux-store/store'
import SimpleSidebar from '@/components/sidebar'
import Navbar from '@/components/navbar'


export default function Home() {
  const incomeData = useAppSelector((state: RootState) =>state.expenses.income
);
const expenseData = useAppSelector((state: RootState) =>state.expenses.expenses
);
  const totalIncome = incomeData.reduce(
    (total, income) => total + Number(income.amount),
    0
  );
const totalExpenses = expenseData.reduce(
  (total, expense) => total + Number(expense.price),
  0
);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Stack
        h={"100vh"}
        w={'100vw'}
      >
        <SimpleSidebar />
        <Stack
          w={{ sm: "100vw", base: "100vw", md: "90vw", lg: "90vw" }}
          ml={{ sm: "none", base: "none", md: "9.5rem", lg: "9.5rem" }}
        >
          <Navbar title="Expenses and Income Summary " />
          <Stack
            direction={{ base: "column", sm: "column", md: "row", lg: "row" }}
            wrap={'wrap'}
          >
        <Stack m={"1rem"} direction={{ base: "column", sm: "column", md: "row", lg: "row" }}>
        <Stack
              border={"1px solid black"}
              borderRadius={"8px"}
              minWidth={"310px"}
              padding={"8px"}
            >
              <Text color={'#8A94A6'}>Total Income</Text>
              <Text fontWeight={'bold'} color={'gray'} fontSize='2rem'>{totalIncome}</Text>
            </Stack>
            <Stack
              minWidth={"310px"}
              padding={"8px"}
              border={"1px solid black"}
              borderRadius={"8px"}
            >
              <Text fontSize={"1rem"} fontWeight={"700"} color={'#8A94A6'}>
                Total Expenses
              </Text>
              <Text fontWeight={'bold'} color={'gray'} fontSize='2rem'>{totalExpenses}</Text>
            </Stack>
            <Stack
              minWidth={"310px"}
              padding={"8px"}
              border={"1px solid black"}
              borderRadius={"8px"}
            >
              <Text fontSize={"1rem"} fontWeight={"700"} color={'#8A94A6'}>
                Total Amount remaining
              </Text>
              <Text fontWeight={'bold'} color={'gray'} fontSize='2rem'>{totalIncome-totalExpenses}</Text>
            </Stack>
        </Stack>

          </Stack>
        </Stack>
        </Stack>
      </main>
    </>
  )
}
