import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Stack ,Text,HStack} from '@chakra-ui/react'
import { useAppSelector } from '@/hooks/dispatchSelectHook'
import { RootState } from '@/services/redux-store/store'
import SimpleSidebar from '@/components/sidebar'
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const incomeData = useAppSelector((state: RootState) =>state.expenses.income
);
const expenseData = useAppSelector((state: RootState) =>state.expenses.expenses
);
  const totalIncome = incomeData.reduce(
    (total, income) => total + Number(income.amount),
    0
  );
const totalExpenses = expenseData.reduce(
  (total, expense) => total + Number(expense.price),
  0
);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Stack
        h={"100vh"}
        w={{ sm: "100vw", base: "100vw", md: "90vw", lg: "90vw" }}
      >
        <SimpleSidebar />
        <Stack
          w={{ sm: "100vw", base: "100vw", md: "90vw", lg: "90vw" }}
          ml={{ sm: "none", base: "none", md: "3rem", lg: "3rem" }}
        >
          <Navbar title="Expenses" />
          <Text ml={"1rem"}>Summary</Text>
          <Stack
            // ml={"1rem"}
            direction={{ base: "column", sm: "column", md: "row", lg: "row" }}
          >
            {/* <h1>Expense Tracker</h1> */}
        <Stack m={"1rem"} direction={{ base: "column", sm: "column", md: "row", lg: "row" }}>
        <Stack
              minWidth={"310px"}
              padding={"8px"}
            >
              <Text fontSize={"1rem"} fontWeight={"700"}>
                Total Income
              </Text>
              <Text>{totalIncome}</Text>
            </Stack>
            <Stack
              minWidth={"310px"}
              padding={"8px"}
            >
              <Text fontSize={"1rem"} fontWeight={"700"}>
                Total Expenses
              </Text>
              <Text>{totalExpenses}</Text>
            </Stack>
            <Stack
              minWidth={"310px"}
              padding={"8px"}
            >
              <Text fontSize={"1rem"} fontWeight={"700"}>
                Total Amount remaining
              </Text>
              <Text>{totalIncome-totalExpenses}</Text>
            </Stack>
        </Stack>

          </Stack>
        </Stack>
        </Stack>
      </main>
    </>
  )
}
